### ISSUE TITLE
Installation of nltk is failing

### ISSUE THREAD

**Issue by elcct** [codelucas/newspaper#121]
Typing `pip install newspaper` gives me this:

```
Collecting nltk==2.0.4 (from newspaper)
  Using cached nltk-2.0.4.tar.gz
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    Extracting in /tmp/tmp_Eucsc
    Now working in /tmp/tmp_Eucsc/distribute-0.6.21
    Building a Distribute egg in /tmp/pip-build-NlC6P4/nltk
    /tmp/pip-build-NlC6P4/nltk/distribute-0.6.21-py2.7.egg
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/tmp/pip-build-NlC6P4/nltk/setup.py", line 32, in <module>
        del sdist.finders[:]
    AttributeError: 'module' object has no attribute 'finders'
    Complete output from command python setup.py egg_info:
    Downloading http://pypi.python.org/packages/source/d/distribute/distribute-0.6.21.tar.gz
    
    Extracting in /tmp/tmp_Eucsc
    
    Now working in /tmp/tmp_Eucsc/distribute-0.6.21
    
    Building a Distribute egg in /tmp/pip-build-NlC6P4/nltk
    
    /tmp/pip-build-NlC6P4/nltk/distribute-0.6.21-py2.7.egg
    
    Traceback (most recent call last):
    
      File "<string>", line 20, in <module>
    
      File "/tmp/pip-build-NlC6P4/nltk/setup.py", line 32, in <module>
    
        del sdist.finders[:]
    
    AttributeError: 'module' object has no attribute 'finders'
```

It seems like a known issue with `nltk`

`nltk 3.0.1` however installs just fine.

**Comment by mattaudesse** [comment]
I just ran into the same problem (Python 2.7 virtualenv on FreeBSD 10.1-RELEASE).

Using markuskiller's advice from [here](https://github.com/nltk/nltk/issues/824) helped me get around it.

**Comment by jwarzech** [comment]
Any advice on getting around this using a Heroku buildpack (I think it locks setuptools at version 11)?
